Repository myeonginjin/kiwi_kiosk, pull requests merged in 2023-06, with the labels that each got.

#22 [KK-17] UI 누락본 추가
  Assets/Assets/Images/Design/Screen/2-1_set.png
  Assets/Assets/Images/Design/Screen/2-2_set_side&drink(blank).png
  Assets/Assets/Images/Design/Screen/2_dessert.png
Labels: bug, enhancement

#25 [Kk-22] VR, interaction 추가 적용
  Assets/Prefabs/Cart Slot.prefab
  Assets/Scenes/Practice.unity
  Assets/TextMesh Pro/Resources/Fonts & Materials/LiberationSans SDF - Fallback.asset
  ProjectSettings/EditorBuildSettings.asset
Labels: enhancement

#29 [KK-16] 실전 모드 구현
  Assets/Assets/Sounds/Other/bgm_main.mp3
  Assets/Assets/Sounds/Other/bgm_main.mp3.meta
  Assets/Assets/Sounds/Voice/11_주문완료.wav.meta
  Assets/Material/Fade Material.mat
  Assets/Material/Fade Material.mat.meta
  Assets/Prefabs/Popup.prefab
  Assets/Prefabs/Scene Loader.prefab
  Assets/Prefabs/Scene Loader.prefab.meta
  Assets/Scenes/Game.unity
  Assets/Scenes/Main.unity
  Assets/Scenes/Practice.unity
  Assets/Scripts/Data/AssistData.cs
  Assets/Scripts/Data/ItemData.cs
  Assets/Scripts/Data/MissionData.cs
  Assets/Scripts/Data/OrderData.cs
  Assets/Scripts/Data/PayData.cs
  Assets/Scripts/Interface/AssistInterface.cs
  Assets/Scripts/Interface/LoadInterface.cs
  Assets/Scripts/Interface/MissionInterface.cs
  Assets/Scripts/Interface/OrderInterface.cs
  Assets/Scripts/Interface/PayInterface.cs
  Assets/Scripts/Service/AssistService.cs
  Assets/Scripts/Service/LoadService.cs
  Assets/Scripts/Service/MissionService.cs
  Assets/Scripts/Service/OrderService.cs
  Assets/Scripts/Service/PayService.cs
  Assets/Scripts/Test.cs
  Assets/Scripts/Test.cs.meta
Labels: enhancement

#30 Kk 25
  Assets/Scenes/Game.unity
  Assets/Scenes/Main.unity
  Assets/Scenes/Practice.unity
Labels: bug

#31 [KK-27] 사용자 메뉴얼 작성
  UserManual.md
Labels: documentation

#32 [KK-27] 사용자 메뉴얼 작성
  UserManual.md
Labels: documentation

#35 23.06.20 배포 ( V1 APP)
  Assets/Assets/Images/Manual.meta
  Assets/Assets/Images/Manual/ex1.png
  Assets/Assets/Images/Manual/ex1.png.meta
  Assets/Assets/Images/Manual/ex2.png
  Assets/Assets/Images/Manual/ex2.png.meta
  Assets/Assets/Images/Manual/ex3.png
  Assets/Assets/Images/Manual/ex3.png.meta
  Assets/Assets/Images/Manual/flow.png
  Assets/Assets/Images/Manual/flow.png.meta
  Assets/Assets/Images/Manual/layer.png
  Assets/Assets/Images/Manual/layer.png.meta
  Assets/Assets/Images/Manual/usecase.png
  Assets/Assets/Images/Manual/usecase.png.meta
  Assets/Assets/Sounds/Other/bgm_main.mp3
  Assets/Assets/Sounds/Other/bgm_main.mp3.meta
  Assets/Assets/Sounds/Voice/11_주문완료.wav.meta
  Assets/Material/Fade Material.mat
  Assets/Material/Fade Material.mat.meta
  Assets/Prefabs/Popup.prefab
  Assets/Prefabs/Scene Loader.prefab
  Assets/Prefabs/Scene Loader.prefab.meta
  Assets/Scenes/Game.unity
  Assets/Scenes/Main.unity
  Assets/Scenes/Practice.unity
  Assets/Scripts/Data/AssistData.cs
  Assets/Scripts/Data/MissionData.cs
  Assets/Scripts/Data/OrderData.cs
  Assets/Scripts/Data/PayData.cs
  Assets/Scripts/Interface/AssistInterface.cs
  Assets/Scripts/Interface/ExitInterface.cs
  Assets/Scripts/Interface/ExitInterface.cs.meta
  Assets/Scripts/Interface/LoadInterface.cs
  Assets/Scripts/Interface/MissionInterface.cs
  Assets/Scripts/Interface/OrderInterface.cs
  Assets/Scripts/Interface/POSInterface.cs
  Assets/Scripts/Interface/PayInterface.cs
  Assets/Scripts/Service/AssistService.cs
  Assets/Scripts/Service/ExitService.cs
  Assets/Scripts/Service/ExitService.cs.meta
  Assets/Scripts/Service/LoadService.cs
  Assets/Scripts/Service/MissionService.cs
  Assets/Scripts/Service/OrderService.cs
  Assets/Scripts/Service/POSService.cs
  Assets/Scripts/Service/PayService.cs
  Assets/Scripts/Test.cs
  Assets/Scripts/Test.cs.meta
  DeveloperManual.md
  README.md
  UserManual.md
Labels: release
